### ISSUE TITLE
SCIP EXCEPTION_ACCESS_VIOLATION In JuMP 1.1.0 and SCIP V0.11.3  on Windows 11

### ISSUE THREAD

**Issue by ChrisNabold** [scipopt/SCIP.jl#237] opened 2022-05-27 12:40 UTC
I am trying to solve a small problem using SCIP.Optimizer using 64 bit version of SCIP . After:
using JuMP, SCIP
model =  Model(SCIP.Optimizer)
@variable(model, 0 <= x <= 2)
@variable(model, 0 <= y <= 30)
@objective(model, Max, 5x + 3 * y)
@constraint(model, con, 1x + 5y <= 3)
optimize!(model) 
I get an exception_Access_Violation
[SCIP_error.txt](https://github.com/scipopt/SCIP.jl/files/8786688/SCIP_error.txt)
-- error message attached as .TXT file ---

I have not received any error message during installation of SCIP in Julia

**Comment by ShuhuaGao** [comment] 2022-06-14 10:01
I have the same issue.

**Comment by matbesancon** [comment] 2022-06-14 10:04
thanks both for reporting. Did you install SCIP separately? As indicated in the README, the BinaryBuilder automatic SCIP build is still buggy for unidentified reasons

**Comment by eduardosalaz** [comment] 2022-07-26 23:49
Similar error, I installed SCIP.jl (0.11.3) directly, Julia 1.6.6, Windows 10, JuMP 1.0. [SCIP_trace.txt](https://github.com/scipopt/SCIP.jl/files/9193927/SCIP_trace.txt), my steps to reproduce are a bit more complicated but I don't think it's specific to my model. If they are needed, I will provide a way to reproduce them.

**Comment by matbesancon** [comment] 2022-09-30 09:34
when you run tests, what are the first lines that appear, the line containing:
```
@show(@eval(SCIP, libscip) == SCIP_jll.libscip)
@show(SCIP_PaPILO_jll.is_available() && @eval(SCIP, libscip) == SCIP_PaPILO_jll.libscip)
```

**Comment by ChrisNabold** [comment] 2022-09-30 12:49
First I installed SCIP.jl using the latest version SCIP 8.0.1. SCIP.jl installed without error message.

Then I tried to run sudoku from www.dev/JuMP.jl/stable/tutorials/linear/sudoku/ <http://www.dev/JuMP.jl/stable/tutorials/linear/sudoku/> 

The example fails after optimize!(sudoku)

Error message: The kernel appears to have died. It will restart automatically

 

Test:

using JuMP, SCIP

sudoku = Model(SCIP.Optimizer)

@***@***.***(SCIP, libscip) == SCIP_jll.libscip)

 

UndefVarError: SCIP_jll not defined

 

Stacktrace:

[1] top-level scope

   @ show.jl:1047

[2] eval

   @ .\boot.jl:368 [inlined]

[3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)

   @ Base .\loading.jl:1428

   

@show(SCIP_PaPILO_jll.is_available() && @eval(SCIP,libscip) == SCIP_PaPILO_jll.libscip)

 

UndefVarError: SCIP_PaPILO_jll not defined

 

Stacktrace:

[1] top-level scope

   @ show.jl:1047

[2] eval

   @ .\boot.jl:368 [inlined]

[3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)

   @ Base .\loading.jl:1428  

 

I hope this will help you

Best regards

Chris Nabold

**Comment by ChrisNabold** [comment] 2022-10-05 06:19
Dear Mathieu,

 

I tried again with the latest version of SCIP.jl

 

After optimize! I receive the error message The kernel appears to have died. It will restart automatically

 

If I insert the two @show requests I receive the error message: UndefVarError: SCIP_jll not defined

 

Stacktrace: 

[1] top-level scope

@show.jl:1047

[2] eval

@.\boot.jl:368 [inlined]

[3] include string (mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)

@Base .\loading.jl:1428

 

I hope this helps

Thank you for your efforts

Regards

Chris

**Comment by matbesancon** [comment] 2022-10-05 06:38
the shown lines should be printed when the tests are run, they are not necessary to add in other tests

**Comment by ChrisNabold** [comment] 2022-10-14 10:24
I just installed the latest version of SCIP V 8.0.2 and the SCIP Interface to JuMP V0.11.7

 

After optimize! I receive the error message The kernel appears to have died. It will restart automatically

 

using JuMP, SCIP

sudoku = Model(SCIP.Optimizer)

@***@***.***(SCIP, libscip) == SCIP_jll.libscip)

 

UndefVarError: SCIP_jll not defined

 

Stacktrace:

[1] top-level scope

   @ show.jl:1047

[2] eval

   @ .\boot.jl:368 [inlined]

[3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)

   @ Base .\loading.jl:1428

   

@show(SCIP_PaPILO_jll.is_available() && @eval(SCIP,libscip) == SCIP_PaPILO_jll.libscip)

 

UndefVarError: SCIP_PaPILO_jll not defined

 

Stacktrace:

[1] top-level scope

   @ show.jl:1047

[2] eval

   @ .\boot.jl:368 [inlined]

[3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)

   @ Base .\loading.jl:1428  

 

I hope this helps you locating the prolem.

 

Regards

Chris

**Comment by matbesancon** [comment] 2022-10-14 10:58
Hi, sorry my bad, it should be:
```
using SCIP_jll, SCIP_PaPILO_jll
@show(@eval(SCIP, libscip) == SCIP_jll.libscip)
@show(SCIP_PaPILO_jll.is_available() && @eval(SCIP, libscip) == SCIP_PaPILO_jll.libscip)
@show(@eval(SCIP, libscip))
```

**Comment by ChrisNabold** [comment] 2022-10-14 11:18
Dear Mathieu,

 

Here is the output with the diagnostics:

After optimize! The kernel dies

 

using JuMP, SCIP, SCIP_jll, SCIP_PaPILO_jll

m = Model(SCIP.Optimizer)

@***@***.***(SCIP, libscip) == SCIP_jll.libscip)

@show(SCIP_PaPILO_jll.is_available() && @eval(SCIP, libscip) == SCIP_PaPILO_jll.libscip)

@***@***.***(SCIP, libscip))

#= In[1]:3 =# @eval(SCIP, libscip) == SCIP_jll.libscip = true

SCIP_PaPILO_jll.is_available() && #= In[1]:4 =# @eval(SCIP, libscip) == SCIP_PaPILO_jll.libscip = false

#= In[1]:5 =# @eval(SCIP, libscip) = "C:\\Users\\Chris\\.julia\\artifacts\\af1d1323a175106a85ac1533571276a5d33ef0b2\\bin\\libscip.dll"

"C:\\Users\\Chris\\.julia\\artifacts\\af1d1323a175106a85ac1533571276a5d33ef0b2\\bin\\libscip.dll"

# Declaring variables

@variable(m, 0<= x1 <=10)

@variable(m, x2 >=0, Int)

@variable(m, x3, Bin)

# Setting the objective

@objective(m, Max, x1 + 2x2 + 5x3)

# Adding constraints

@constraint(m, constraint1, -x1 +  x2 + 3x3 <= -5)

@constraint(m, constraint2,  x1 + 3x2 - 7x3 <= 10)

# Printing the prepared optimization model

print(m)

# Solving the optimization problem

JuMP.optimize!(m)

# Printing the optimal solutions obtained

println("Optimal Solutions:")

println("x1 = ", JuMP.value(x1))

println("x2 = ", JuMP.value(x2))

println("x3 = ", JuMP.value(x3))

​

maxSubject to𝑥1+2𝑥2+5𝑥3−𝑥1+𝑥2+3𝑥3≤−5.0𝑥1+3𝑥2−7𝑥3≤10.0𝑥1≥0.0𝑥2≥0.0𝑥1≤10.0𝑥2∈ℤ𝑥3∈{0,1}

 

best regards

Chris

**Comment by matbesancon** [comment] 2022-10-14 11:50
as indicated, the automatic JLL package does not work on windows for now, this is a known issue, the instructions are similar to that one:
https://github.com/scipopt/SCIP.jl/issues/248
See https://github.com/scipopt/SCIP.jl#update-august-2020 that part of the readme.

You need to install SCIP yourself, set an environment variable SCIPOPTDIR and run build SCIP in package mode

**Comment by ChrisNabold** [comment] 2022-10-14 12:05
Thank you for your comment. I installed SCIP Optsuite 8.0.2 before installing SCIP.jl

I also tried Build(SCIP)

All with no success

**Comment by matbesancon** [comment] 2022-10-14 12:14
you need to install SCIP (like you did) but then you need to follow the instructions

**Comment by ChrisNabold** [comment] 2022-10-14 12:21
I think I installed the SCIP interface as described.

I installed SCIP V8.0.2

Added the SCIPOPTDIR variable into the system

Installed SCIP in Julia -> no error message

 

What am I missing?

 

Thank you for your comment

Chris

 

 

 

from: Mathieu Besançon ***@***.***> 
Sent: Friday, 14 October 2022 14:15
To: scipopt/SCIP.jl ***@***.***>
Cc: ChrisNabold ***@***.***>; Author ***@***.***>
Subject: Re: [scipopt/SCIP.jl] SCIP EXCEPTION_ACCESS_VIOLATION In JuMP 1.1.0 and SCIP V0.11.3 on Windows 11 (Issue #237)

 

Reopened #237 <https://github.com/scipopt/SCIP.jl/issues/237> .

**Comment by matbesancon** [comment] 2022-10-14 12:27
did you build SCIP? It should then pick up the SCIPOPTDIR environment variable

**Comment by ChrisNabold** [comment] 2022-10-14 13:21
I checked the variable SCIPOPTDIR “c:\program files\ScipoptSuite 8.0.2\bin

There are only two elements libscip.dll and scip.exe  but no scip.dll

 

So this seems to be the problem with the windows install

 

Installing and build of SCIP.jl does not give any error message.

Including SCIP.exe doesn’t help either

 

Thank you for your comments

Chris

**Comment by matbesancon** [comment] 2022-10-14 13:36
> There are only two elements libscip.dll and scip.exe  but no scip.dll

yes `libscip.dll` is the expected file

**Comment by matbesancon** [comment] 2022-10-14 13:36
do you have the latest SCIP.jl version?

**Comment by lilanger** [comment] 2022-11-08 16:35
Hi Matt,
I have the same error (see below) when trying to use SCIP in SpineOpt. This is what I did:
````
julia> ENV["SCIPOPTDIR"]="C:\\Program Files\\SCIPOptSuite 8.0.2\\"
"C:\\Program Files\\SCIPOptSuite 8.0.2\\"

(Skive) pkg> build SCIP
    Building SCIP → `C:\Users\lilang\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\60d5d10daa0a6eeb5befc3fb44a14fe8d9da3a5f\build.log`

julia> @eval SCIP libscip
"C:\\Users\\lilang\\.julia\\artifacts\\af1d1323a175106a85ac1533571276a5d33ef0b2\\bin\\libscip.dll"

julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
````
This is the error log running it in the spinetoolbox:
````
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x624e0000 -- unknown function (ip: 00000000624e0000)
in expression starting at C:\Users\lilang\.spinetoolbox\plugins\SpineOpt\specifications\Tool\run_spineopt.jl:3
unknown function (ip: 00000000624e0000)
Allocations: 265425759 (Pool: 265340240; Big: 85519); GC: 185

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0xc64a5b0c -- SCIPprobFree at C:\Users\lilang\.julia\artifacts\af1d1323a175106a85ac1533571276a5d33ef0b2\bin\libscip.dll (unknown line)
in expression starting at C:\Users\lilang\.spinetoolbox\plugins\SpineOpt\specifications\Tool\run_spineopt.jl:3
SCIPprobFree at C:\Users\lilang\.julia\artifacts\af1d1323a175106a85ac1533571276a5d33ef0b2\bin\libscip.dll (unknown line)
SCIPfreeTransform at C:\Users\lilang\.julia\artifacts\af1d1323a175106a85ac1533571276a5d33ef0b2\bin\libscip.dll (unknown line)
SCIPfreeProb at C:\Users\lilang\.julia\artifacts\af1d1323a175106a85ac1533571276a5d33ef0b2\bin\libscip.dll (unknown line)
SCIPfree at C:\Users\lilang\.julia\artifacts\af1d1323a175106a85ac1533571276a5d33ef0b2\bin\libscip.dll (unknown line)
SCIPfree at C:\Users\lilang\.julia\packages\SCIP\q1bt3\src\LibSCIP.jl:3878
unknown function (ip: 000000007c1708f5)
macro expansion at C:\Users\lilang\.julia\packages\SCIP\q1bt3\src\wrapper.jl:11 [inlined]
free_scip at C:\Users\lilang\.julia\packages\SCIP\q1bt3\src\scip_data.jl:70
free_scip at C:\Users\lilang\.julia\packages\SCIP\q1bt3\src\MOI_wrapper.jl:60
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1788 [inlined]
run_finalizer at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:278
jl_gc_run_finalizers_in_list at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:365
run_finalizers at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:394 [inlined]
run_finalizers at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:372
jl_atexit_hook at /cygdrive/c/buildbot/worker/package_win64/build/src\init.c:240
jl_exit at /cygdrive/c/buildbot/worker/package_win64/build/src\jl_uv.c:633
jl_exception_handler at /cygdrive/c/buildbot/worker/package_win64/build/src\signals-win.c:321
__julia_personality at /cygdrive/c/buildbot/worker/package_win64/build/src/support\win32_ucontext.c:28
_chkstk at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlRaiseException at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
KiUserExceptionDispatcher at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
unknown function (ip: 00000000624dffff)
Allocations: 265425759 (Pool: 265340240; Big: 85519); GC: 185
Optimizing model simple...
Kernel died (×_×)
````
This is the error log when running it in the julia repl:
````
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0xb6a30000 -- unknown function (ip: 00000000b6a30000)
in expression starting at REPL[10]:1
unknown function (ip: 00000000b6a30000)
Allocations: 336401353 (Pool: 336287850; Big: 113503); GC: 215
````
Thanks for helping!

**Comment by lilanger** [comment] 2022-11-15 15:36
For some reason it worked now, after setting this variable and building SCIP:

![image](https://user-images.githubusercontent.com/54096244/201960614-f960af5f-945f-4018-976b-aa4dd219b1a1.png)

**Comment by Timeroot** [comment] 2023-04-18 20:12
It seems the problem happens when you build SCIP once without setting the SCIPOPTDIR environment variable; subsequently rebuilding doesn't automatically fix it. Doing `Pkg.rm("SCIP")` isn't enough. Here's what I did that finally worked, after a lot of things (based on advice above) that wasn't quite enough:
 * `import Pkg; Pkg.rm(["SCIP","SCIP_jll","SCIP_PaPILO_jll"])`. (You might only need `Pkg.rm("SCIP")`.
 * Deleted the `SCIP`, `SCIP_jll`, and `SCIP_PaPILO_jll` directories in `.julia/packages` and `.julia/compiled`.
 * Set a global environment variable for SCIPOPTDIR. You can set SCIPOPTDIR any time you'd want to update SCIP, but this is ... probably safer.
 * **Restart jupyter**, because restarting the kernel isn't enough: as long as jupyter is open, it doesn't pull in any new environment variables.
 * Check that `ENV["SCIPOPTDIR"]` should be set as soon as you open a new julia kernel.
 * Run `Pkg.add("SCIP"); Pkg.build("SCIP");`
 * Check `import SCIP; println(SCIP.libscip)`. It should be something like "C:\\Program Files\\SCIPOptSuite 8.0.3\\bin\\libscip.dll" (or whatever you SCIPOPTDIR is), and not anything with `.julia/artifacts/...`.

**Comment by matbesancon** [comment] 2023-04-19 06:46
thanks a lot for the detailed report, that's very helpful! Feel free to add a PR to the readme to add specific windows instructions.

**Comment by matbesancon** [comment] 2023-11-17 08:46
Closing this in the meantime

**Closed by matbesancon** 2023-11-17 08:46 UTC
